### ISSUE TITLE
报错：KeyError: 'mblog'

### ISSUE THREAD

**Issue by MHYPS** [cndiandian/weibo#11]
两个星期前就这样了......
Traceback (most recent call last):
  File "G:\ruanjian\1 排除项\weibo-master\weibo.py", line 193, in <module>
    weibo.run()
  File "G:\ruanjian\1 排除项\weibo-master\weibo.py", line 164, in run
    if item['mblog']['isLongText']: # 如果博文包含全文 则去解析完整微博
KeyError: 'mblog'

**Comment by MHYPS** [comment]
现在抓取几条微博之后就会停止，重启之后偶尔能运行，多数情况下无济于事

**Comment by cndiandian** [comment]
抱歉才注意到问题，如果还有遇到问题，请通过readme中的微信联系我，会尽快解决。
