### ISSUE TITLE
你好报错 能帮忙看看不

### ISSUE THREAD

**Issue by coderykw** [cndiandian/weibo#16]
Traceback (most recent call last):
  File "C:\Users\ss\Downloads\weibo-master1\weibo-master\weibo.py", line 208, in <module>
    weibo.run()
  File "C:\Users\ss\Downloads\weibo-master1\weibo-master\weibo.py", line 197, in run
    self.parse_weibo(weibo)
  File "C:\Users\ss\Downloads\weibo-master1\weibo-master\weibo.py", line 77, in parse_weibo
    cursor.execute(sql, (weibo['link'],))
sqlite3.OperationalError: no such table: weibo

**Comment by cndiandian** [comment]
我在本地和服务器测试都没问题，麻烦添加一下readme中的微信，我远程看看，怀疑是目录的问题
