### ISSUE TITLE
长微博parse失败

### ISSUE THREAD

**Issue by LouisFinner** [cndiandian/weibo#8]
对于字数比较长被折叠起来的微博找不到pics关键词

Traceback (most recent call last):
  File "weibo.py", line 191, in <module>
    weibo.run()
  File "weibo.py", line 163, in run
    self.get_weibo_detail(item['mblog']['bid'])
  File "weibo.py", line 140, in get_weibo_detail
    weibo['pics'] = [pic['large']['url'] for pic in detail['data']['pics']]
KeyError: 'pics'

**Comment by cndiandian** [comment]
已修复

实际原因是因为解析长微博的时候，没有判断是否有配图，导致获取图片的时候抛出异常了。
